baseURL = "https://matagus.alameda.dev/"
title = "matagus"
theme = "hugo-ink"
paginate = 5
DefaultContentLanguage = "en"
languageCode = "en-us"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true
googleAnalytics = "UA-1607174-15"
disqusShortname = "matagus-github-io"

[permalinks]
  posts = "/:year/:month/:title/"
  quotes = "/:year/:month/:title/"

[languages]
  [languages.es]
    languageName = "Espa√±ol"
    copyright = "¬© Copyright"
    weight = 2
  [languages.en]
    languageName = "English"
    weight = 1
    copyright = "¬© Copyright"

[params]
	subtitle = "current status: üêº"

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"
    avatar = "https://1.gravatar.com/avatar/db3b3decf3a49e94f49172034f5df598?s=64&d=mm"

    mainSections = ["posts", "quotes"]

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	#mode = "auto" # "dark" or "auto"
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "All posts"
url = "/posts/"
weight = 2

[[languages.en.menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[languages.en.menu.main]]
name = "About me"
url = "/about-me/"
weight = 4

[[languages.es.menu.main]]
name = "Home"
url = "/es/"
weight = 1

[[languages.es.menu.main]]
name = "Art√≠culos"
url = "/es/posts/"
weight = 2

[[languages.es.menu.main]]
name = "Etiquetas"
url = "/es/tags/"
weight = 3

[[languages.es.menu.main]]
name = "Sobre m√≠"
url = "/es/sobre-mi/"
weight = 4

[[params.social]]
name = "Books I'm reading"
icon = "book"
url = "https://www.goodreads.com/user/show/4930036-matagus"

[[params.social]]
name = "Posts I'm reading"
icon = "file"
url = "https://getpocket.com/@644ged34p1974A24b3T6c35T1cA8p1a87f4p05Vb62Ge0lg268647e5bFe9Jd3a0"

[[params.social]]
name = "Listening to"
icon = "music"
url = "https://mixcloud.com/matagus"

[[params.social]]
name = "StackOverflow"
icon = "edit"
url = "https://stackoverflow.com/users/3219121/matagus"

[[params.social]]
name = "Github Profile"
icon = "github"
url = "https://github.com/matagus"

[[params.social]]
name = "RSS Feed"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
